### ISSUE TITLE
Android Basics: Adaptive Layouts - nav back error after rotating the device 

### ISSUE THREAD

**Issue by tobiasgru** [google-developer-training/basic-android-kotlin-training-sports#2]
on a small device, if you go to the details pane and rotate the device to landscape the back button takes you to the home screen. You can't go back to the list pane without restarting the app

**Comment by Wavey1287** [comment]
Yup, this is broken and I've been trying to fix it on my own to no affect.  

Calling .closePane() and .close() on the slidingPaneLayout, at any stage in the lifecycle isn't working.  It does nothing.  Apparently that is deprecated now?  But how to do it instead is unclear.  

Calling either .close on the back buttons init function does nothing.  It's already in the handleOnBackPressed, but apparently that does nothing when the main activity doesn't apparently even realize that the pane is open.  

I think this is broken in the SlidingPaneLayout file itself.  This is an issue I will be putting on the official Google Developer issue report page, see if it gets assigned to someone.

**Google Developers, you should show how to fix this.  This whole tutorial is worthless if the final app doesn't even do what you tried to have it do.**  @yenerm @tobiasgru @lmoroney @jtavva 

https://issuetracker.google.com/issues/236690161
